name: Test
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ansible
